# Gitpod Configuration
# ver: https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml

# Uso de imagen de Docker específica
# ver: https://hub.docker.com/u/gitpod
image: gitpod/workspace-java-23

# Comandos a ejecutar al inicio del proyecto
# - primera vez : before --> init --> command
# - al reiniciar: before --> command
tasks:

  - name: Compila proyecto sin ejecutar pruebas
    # before se ejecuta siempre
    before: |
      sdk env install

    # init se ejecuta solo la primera vez
    init: |
      if [ -f pom.xml ]; then mvn package -DskipTests; fi

    # command se ejecuta para iniciar servicios
    command: |
      if [ -f docker-compose.yml ]; then docker compose up -d; fi

# Extensiones
vscode:
  extensions:
      - "vscjava.vscode-java-pack"
      - "vmware.vscode-boot-dev-pack"
      - "ms-vscode.live-server"
      - "jebbs.plantuml"

