@startuml "casos-de-uso"
left to right direction
skinparam packageStyle rectangle

actor deportista
rectangle CycleTrainer {
  deportista -- (Iniciar trayecto)
  deportista -- (Agregar ubicación al Trayecto)
  deportista -- (Finalizar Trayecto)
  deportista -- (Consultar Trayecto)
  deportista -- (Consultar todos los Trayectos)
}

@enduml